version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
       - KC_BOOTSTRAP_ADMIN_USERNAME=admin # Имя временного администратора
       - KC_BOOTSTRAP_ADMIN_PASSWORD=admin_password # Пароль временного администратора
    ports:
      - 8080:8080
    command: start-dev
    volumes:
      - ./keycloak:/opt/jboss/keycloak/standalone/data